# Generated by Django 4.1.3 on 2022-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
