# Generated by Django 4.1.3 on 2022-12-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contact_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
